version: '3.8'

services:
  user-service:
    build: ./services/user-service  # Vérifiez que le chemin est correct
    container_name: user-service
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/reservationsdb
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - postgres
      - kafka
    restart: always

  salle-service:
    build: ./services/salle-service  # Vérifiez que le chemin est correct
    container_name: salle-service
    ports:
      - "5002:5000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/reservationsdb
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - postgres
      - kafka
    restart: always

  reservation-service:
    build: ./services/reservation-service  # Vérifiez que le chemin est correct
    container_name: reservation-service
    ports:
      - "5003:5000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/reservationsdb
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - postgres
      - kafka
    restart: always

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: reservationsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

volumes:
  postgres_data:

