apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  loki.yaml: |
    server:
      http_listen_port: 3100
    distributor:
      ring:
        kvstore:
          store: inmemory
    ingester:
      chunk_target_size: 1048576
      max_chunk_age: 1h
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/index
        cache_location: /data/loki/cache
        shared_store: filesystem
      filesystem:
        directory: /data/loki/chunks
    limits_config:
      max_streams_per_user: 1000
    chunk_target_size: 1048576
