apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  config.yaml: |
    server:
      http_listen_port: 9080
    clients:
      - url: http://loki:3100/api/prom/push
    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: app
