apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
spec:
  schedule: "0 0 * * *"  # Exécution tous les jours à minuit
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: postgres:15  # Utilise l'image officielle PostgreSQL
              command: ["/bin/bash", "-c", "/scripts/backup.sh"]
              volumeMounts:
                - name: backup-scripts
                  mountPath: /scripts
                - name: backup-storage
                  mountPath: /backups  # L'emplacement de stockage des sauvegardes
          restartPolicy: OnFailure
          volumes:
            - name: backup-scripts
              configMap:
                name: backup-scripts  # Utilisation d'un ConfigMap pour les scripts
            - name: backup-storage
              persistentVolumeClaim:
                claimName: backup-pvc  # PVC pour stocker les sauvegardes
