apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 0  # Réduction du nombre de réplicas à 0 pour ne pas recréer les pods
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: leith21/user-service:latest  # DockerHub image for the user-service
          ports:
            - containerPort: 5001  # Port exposed inside the container for Flask
          env:
            - name: DATABASE_URL
              value: postgresql://admin:admin@postgres:5432/reservationsdb  # Corrected PostgreSQL service name
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092  # Corrected Kafka service name
          # Health checks
          readinessProbe:
            httpGet:
              path: /users
              port: 5001  # Corrected to port 5001 for readiness check
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /users
              port: 5001  # Corrected to port 5001 for liveness check
            initialDelaySeconds: 15
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 5001  # Exposing service on port 5001
      targetPort: 5001  # Corrected to target port 5001
  type: LoadBalancer  # Change to LoadBalancer for external access

