apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: leith21/user-service:latest  # DockerHub image for the user-service
          ports:
            - containerPort: 5000  # Port exposed inside the container for Flask
          env:
            - name: DATABASE_URL
              value: postgresql://admin:admin@postgres:5432/reservationsdb  # Corrected PostgreSQL service name
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092  # Corrected Kafka service name
          # Health checks
          readinessProbe:
            httpGet:
              path: /users
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /users
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP  # Change to LoadBalancer if you want to expose externally

