apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 5001        # Port utilisé par les autres services pour accéder à user-service
      targetPort: 5000  # Port exposé à l'intérieur du container Flask
  type: ClusterIP

