replicaCount: 1

image:
  repository: leith21/reservation-service
  tag: latest
  pullPolicy: Always

service:
  name: reservation-service
  type: ClusterIP
  port: 5000

env:
  DATABASE_URL: postgresql://admin:admin@postgres:5432/reservationsdb
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092

resources: {}
