apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-salle-service
  labels:
    app: {{ .Release.Name }}-salle-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-salle-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-salle-service
    spec:
      containers:
        - name: salle-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DATABASE_URL
              value: {{ .Values.env.DATABASE_URL }}
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.env.KAFKA_BOOTSTRAP_SERVERS }}
