apiVersion: apps/v1
kind: Deployment
metadata:
  name: salle-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: salle-service
  template:
    metadata:
      labels:
        app: salle-service
    spec:
      containers:
        - name: salle-service
          image: leith21/salle-service:latest  # Assurez-vous que l'image est correcte
          ports:
            - containerPort: 5002
          env:
            - name: DATABASE_URL
              value: postgresql://admin:admin@postgres:5432/reservationsdb  # PostgreSQL service
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092  # Kafka service
          # Health checks
          readinessProbe:
            httpGet:
              path: /salles
              port: 5002
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /salles
              port: 5002
            initialDelaySeconds: 15
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: salle-service
spec:
  selector:
    app: salle-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP  # Change to LoadBalancer if you want to expose externally

