apiVersion: apps/v1
kind: Deployment
metadata:
  name: salle-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: salle-service
  template:
    metadata:
      labels:
        app: salle-service
    spec:
      containers:
        - name: salle-service
          image: lkassous/salle-service:latest  # Remplace si nécessaire
          ports:
            - containerPort: 5002
          env:
            - name: DATABASE_URL
              value: postgresql://admin:admin@postgres:5432/reservationsdb
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
