name: CI/CD Pipeline for Room Reservation System

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the main branch

jobs:
  # Job for building Docker images and pushing them to DockerHub
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx to build the images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to DockerHub using the GitHub secrets
      - name: Log in to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Build and push Docker images for each service
      - name: Build and push user-service Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service:latest ./services/user-service
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest

      - name: Build and push salle-service Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/salle-service:latest ./services/salle-service
          docker push ${{ secrets.DOCKER_USERNAME }}/salle-service:latest

      - name: Build and push reservation-service Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/reservation-service:latest ./services/reservation-service
          docker push ${{ secrets.DOCKER_USERNAME }}/reservation-service:latest

  # Job for deploying to Kubernetes after the Docker images are pushed
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push  # Ensures this job runs after the build-and-push job

    steps:
      # Set up Kubernetes config
      - name: Set up Kubernetes config
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

      # Deploy each service to Kubernetes
      - name: Deploy user-service to Kubernetes
        run: kubectl apply -f k8s/user-service/deployment.yaml

      - name: Deploy salle-service to Kubernetes
        run: kubectl apply -f k8s/salle-service/deployment.yaml

      - name: Deploy reservation-service to Kubernetes
        run: kubectl apply -f k8s/reservation-service/deployment.yaml

